DROP TABLE IF EXISTS OW_Characters;
CREATE TABLE OW_Characters (	
	OWC_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	OWC_NAME VARCHAR(50) NOT NULL
);

INSERT INTO OW_Characters (OWC_NAME)	
SELECT 'Genji'  	UNION ALL
SELECT 'McCree' 	UNION ALL
SELECT 'Pharah' 	UNION ALL
SELECT 'Reaper' 	UNION ALL
SELECT 'Soldier:76' UNION ALL
SELECT 'Tracer' 	UNION ALL
SELECT 'Bastion' 	UNION ALL
SELECT 'Hanzo'  	UNION ALL
SELECT 'Junkrat' 	UNION ALL
SELECT 'Mei' 		UNION ALL
SELECT 'Torbjorn' 	UNION ALL
SELECT 'Widowmaker' UNION ALL
SELECT 'D.Va' 		UNION ALL
SELECT 'Reinhardt' 	UNION ALL
SELECT 'Roadhog' 	UNION ALL
SELECT 'Winston' 	UNION ALL
SELECT 'Zarya' 		UNION ALL
SELECT 'Lucio' 		UNION ALL
SELECT 'Mercy' 		UNION ALL
SELECT 'Symmetra' 	UNION ALL
SELECT 'Zenyatta';

DROP TABLE IF EXISTS OW_Game_Mode;
CREATE TABLE OW_Game_Mode (
	OWG_ID INT NOT NULL PRIMARY KEY,
	OWG_DESCRIPTION VARCHAR(50) NOT NULL,
	OWG_OFFENCE_DEFENCE_FLAG INT(1) NOT NULL
);
INSERT INTO OW_Game_Mode (OWG_ID, OWG_DESCRIPTION, OWG_OFFENCE_DEFENCE_FLAG) 
SELECT 1, 'Assault' , 1 UNION ALL
SELECT 2, 'Escort'  , 1 UNION ALL
SELECT 3, 'Hybrid'  , 1 UNION ALL
SELECT 4, 'Control' , 0;

DROP TABLE IF EXISTS OW_Maps;
CREATE TABLE OW_Maps (
	OWM_ID INT NOT NULL PRIMARY KEY,
	OWM_MAP_NAME VARCHAR(50) NOT NULL,
	OWM_OWG_ID INT
);
INSERT INTO OW_Maps (OWM_ID, OWM_MAP_NAME, OWM_OWG_ID)
SELECT 1 , 'Hanamura',				1 UNION ALL
SELECT 2 , 'Temple of Anubis',		1 UNION ALL
SELECT 3 , 'Volskaya Industries',	1 UNION ALL
SELECT 4 , 'Watchpoint: Gibraltar',	2 UNION ALL
SELECT 5 , 'Dorado',			   	2 UNION ALL
SELECT 6 , 'Route 66', 			   	2 UNION ALL
SELECT 7 , 'King''s Row',			3 UNION ALL
SELECT 8 , 'Numbani',				3 UNION ALL
SELECT 9 , 'Hollywood',				3 UNION ALL
SELECT 10, 'Lijiang Tower',			4 UNION ALL
SELECT 11, 'Nepal',					4 UNION ALL
SELECT 12, 'Ilios',					4; 

DROP TABLE IF EXISTS OW_Teams;
CREATE TABLE OW_Teams (
	OWT_ID	INT	PRIMARY KEY NOT NULL,
	OWT_Name VARCHAR(20) NOT NULL
);
INSERT INTO OW_Teams (OWT_Name)
SELECT 1, 'Offence' UNION ALL
SELECT 2, 'Defence';