DROP TABLE IF EXISTS OW_Heroes;
CREATE TABLE OW_Heroes(	
	OWH_ID INT NOT NULL PRIMARY KEY,
	OWH_NAME VARCHAR(50) NOT NULL
);

INSERT INTO OW_Heroes (OWH_ID, OWH_NAME)	
SELECT 1, 'Genji'  		UNION ALL
SELECT 2, 'McCree' 		UNION ALL
SELECT 3, 'Pharah' 		UNION ALL
SELECT 4, 'Reaper' 		UNION ALL
SELECT 5, 'Soldier:76' 	UNION ALL
SELECT 6, 'Tracer' 		UNION ALL
SELECT 7, 'Bastion' 	UNION ALL
SELECT 8, 'Hanzo'  		UNION ALL
SELECT 9, 'Junkrat' 	UNION ALL
SELECT 10, 'Mei' 		UNION ALL
SELECT 11, 'Torbjorn' 	UNION ALL
SELECT 12, 'Widowmaker' UNION ALL
SELECT 13, 'D.Va' 		UNION ALL
SELECT 14, 'Reinhardt' 	UNION ALL
SELECT 15, 'Roadhog' 	UNION ALL
SELECT 16, 'Winston' 	UNION ALL
SELECT 17, 'Zarya' 		UNION ALL
SELECT 18, 'Lucio' 		UNION ALL
SELECT 19, 'Mercy' 		UNION ALL
SELECT 20, 'Symmetra' 	UNION ALL
SELECT 21, 'Zenyatta';

DROP TABLE IF EXISTS OW_Game_Mode;
CREATE TABLE OW_Game_Mode (
	OWG_ID INT NOT NULL PRIMARY KEY,
	OWG_DESCRIPTION VARCHAR(50) NOT NULL,
	OWG_OFFENCE_DEFENCE_FLAG INT(1) NOT NULL
);
INSERT INTO OW_Game_Mode (OWG_ID, OWG_DESCRIPTION, OWG_OFFENCE_DEFENCE_FLAG) 
SELECT 1, 'Assault' , 1 UNION ALL
SELECT 2, 'Escort'  , 1 UNION ALL
SELECT 3, 'Hybrid'  , 1 UNION ALL
SELECT 4, 'Control' , 0;

DROP TABLE IF EXISTS OW_Maps;
CREATE TABLE OW_Maps (
	OWM_ID INT NOT NULL PRIMARY KEY,
	OWM_MAP_NAME VARCHAR(50) NOT NULL,
	OWM_OWG_ID INT
);
INSERT INTO OW_Maps (OWM_ID, OWM_MAP_NAME, OWM_OWG_ID)
SELECT 1 , 'Hanamura',				1 UNION ALL
SELECT 2 , 'Temple of Anubis',		1 UNION ALL
SELECT 3 , 'Volskaya Industries',	1 UNION ALL
SELECT 4 , 'Watchpoint: Gibraltar',	2 UNION ALL
SELECT 5 , 'Dorado',			   	2 UNION ALL
SELECT 6 , 'Route 66', 			   	2 UNION ALL
SELECT 7 , 'King''s Row',			3 UNION ALL
SELECT 8 , 'Numbani',				3 UNION ALL
SELECT 9 , 'Hollywood',				3 UNION ALL
SELECT 10, 'Lijiang Tower',			4 UNION ALL
SELECT 11, 'Nepal',					4 UNION ALL
SELECT 12, 'Ilios',					4; 

DROP TABLE IF EXISTS OW_Teams;
CREATE TABLE OW_Teams (
	OWT_ID	INT	PRIMARY KEY NOT NULL,
	OWT_NAME VARCHAR(20) NOT NULL
);
INSERT INTO OW_Teams (OWT_ID, OWT_Name)
SELECT 1, 'Offence' UNION ALL
SELECT 2, 'Defence';


DROP TABLE IF EXISTS OW_Strats;
CREATE TABLE OW_Strats (
	OWS_ID	INT	PRIMARY KEY NOT NULL AUTO_INCREMENT,
	OWS_TITLE VARCHAR(50) NULL,
	OWS_DESCRIPTION VARCHAR(2500) NOT NULL,
	OWS_OWM_ID INT NULL,
	OWS_OWG_ID INT NULL,
	OWS_OWT_ID INT NULL,
	OWS_CHARACTER_1 INT NULL,
	OWS_CHARACTER_2 INT NULL,
	OWS_CHARACTER_3 INT NULL,
	OWS_CHARACTER_4 INT NULL,
	OWS_CHARACTER_5 INT NULL,
	OWS_CHARACTER_6 INT NULL
);
INSERT INTO OW_Strats (	OWS_TITLE, OWS_DESCRIPTION, OWS_OWM_ID, OWS_OWG_ID, OWS_OWT_ID, OWS_CHARACTER_1, OWS_CHARACTER_2,OWS_CHARACTER_3, OWS_CHARACTER_4, OWS_CHARACTER_5, OWS_CHARACTER_6) 
SELECT 'Go Bananas','Play every character as Winston',NULL,NULL,NULL,16,16,16,16,16,16 UNION ALL
SELECT 'Rolling Thunder','Set up 4 bastions on the payload in turret form while being shielded by Reinhardt',4,2,1,7,7,14,14,7,7 UNION ALL
SELECT 'Dick Move','Play every character as Bastion and sit on the objective',NULL,NULL,2,7,7,7,7,7,7 UNION ALL
SELECT 'Cold Shoulder','With every player as Mei, defend the objective by building ice walls on every entrance to the objective',1,1,2,10,10,10,10,10,10;